### ISSUE TITLE
URDF cannot be loaded

### ISSUE THREAD

**Issue by badriawan** [Robotisim/robotics_software_engineer#35]
### Describe your issue

try to launch using rviz.launch.py on module Robot Creation URDF on video Robot Structure Tree with URDF . Follow all of the instructions and script but urdf link cannot appear on RVIZ and error happened

### Steps to reproduce ( commands you ran - in order )

ros2 launch rviz.launch.py

### What was the expected result?

base link , camera link , and lidar link

### Put here any screenshots or videos link

[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [1434404]
[INFO] [rviz2-2]: process started with pid [1434406]
[robot_state_publisher-1] [WARN] [1720496664.997129607] [robot_state_publisher]: No robot_description parameter, but command-line argument available.  Assuming argument is name of URDF file.  This backwards compatibility fallback will be removed in the future.
[robot_state_publisher-1] Error:   Error reading end tag.
[robot_state_publisher-1]          at line 100 in ./urdf_parser/src/model.cpp
[robot_state_publisher-1] Failed to parse robot description using: urdf_xml_parser/URDFXMLParser
[robot_state_publisher-1] terminate called after throwing an instance of 'std::runtime_error'
[robot_state_publisher-1]   what():  Unable to initialize urdf::model from robot description
[rviz2-2] [INFO] [1720496665.322212801] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1720496665.322436413] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-2] [INFO] [1720496665.351467833] [rviz2]: Stereo is NOT SUPPORTED
[ERROR] [robot_state_publisher-1]: process has died [pid 1434404, exit code -6, cmd '/opt/ros/humble/lib/robot_state_publisher/robot_state_publisher /home/yusuf/ros2_ws/install/ros_fundamental/share/ros_fundamental/urdf/diff_drive.urdf --ros-args'].
[INFO] [rviz2-2]: process has finished cleanly [pid 1434406]

**Comment by badriawan** [comment]
This is my urdf file : 

<?xml version="1.0"?>
<robot name="differential_drive_robot">

  
  <link name="base_link">
  <link name="caster">
  <link name="camera">
  <link name="lidar">

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera"/>
    <origin xyz="0.35 0.0 0.01" rpy="0.0 0.0 3.14"/>
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar"/>
    <origin xyz="-0.285 0.0 0.075" rpy="0.0 0.0 1.57"/>
    <axis xyz="0.0 0.0 1.0"/>
  </joint>



</robot>

**Comment by badriawan** [comment]
This is my urdf file 
`<?xml version="1.0"?>
<robot name="differential_drive_robot">

  
  <link name="base_link">
  <link name="caster">
  <link name="camera">
  <link name="lidar">

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera"/>
    <origin xyz="0.35 0.0 0.01" rpy="0.0 0.0 3.14"/>
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar"/>
    <origin xyz="-0.285 0.0 0.075" rpy="0.0 0.0 1.57"/>
    <axis xyz="0.0 0.0 1.0"/>
  </joint>



</robot>
`

**Comment by noshluk2** [comment]
In line 5 to 8 , where link tags are created 
tags are not closed

it should have `/>` at the end

for example : 
<link name="base_link" />
