### ISSUE TITLE
Gazebo Turtlebot 3 error

### ISSUE THREAD

**Issue by badriawan** [Robotisim/robotics_software_engineer#36]
### Describe your issue

i cannot launch turtlebot3_gazebo turtlebot3_world.launch.py

### Steps to reproduce ( commands you ran - in order )

i cannot launch turtlebot3_gazebo turtlebot3_world.launch.py

### What was the expected result?

launch gazebo world

### Put here any screenshots or videos link

![Screenshot from 2024-07-22 10-53-15](https://github.com/user-attachments/assets/c334bc7c-a1e7-453c-be8e-1ab21d7ccb2e)

**Comment by noshluk2** [comment]
Kindly provide log of terminal .

Install htop and kill gzserver 

gazebo is running in backgroudn

**Comment by badriawan** [comment]
[INFO] [launch]: All log files can be found below /home/yusuf/.ros/log/2024-07-22-20-23-26-162381-yusuf-HP-ENVY-Laptop-13-ad1xx-326835
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : turtlebot3_waffle.urdf
urdf_file_name : turtlebot3_waffle.urdf
[INFO] [gzserver-1]: process started with pid [326856]
[INFO] [gzclient-2]: process started with pid [326858]
[INFO] [robot_state_publisher-3]: process started with pid [326860]
[INFO] [spawn_entity.py-4]: process started with pid [326862]
[robot_state_publisher-3] [INFO] [1721654608.190882403] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-3] [INFO] [1721654608.191016193] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1721654608.191032394] [robot_state_publisher]: got segment base_scan
[robot_state_publisher-3] [INFO] [1721654608.191040738] [robot_state_publisher]: got segment camera_depth_frame
[robot_state_publisher-3] [INFO] [1721654608.191048427] [robot_state_publisher]: got segment camera_depth_optical_frame
[robot_state_publisher-3] [INFO] [1721654608.191056408] [robot_state_publisher]: got segment camera_link
[robot_state_publisher-3] [INFO] [1721654608.191063784] [robot_state_publisher]: got segment camera_rgb_frame
[robot_state_publisher-3] [INFO] [1721654608.191071096] [robot_state_publisher]: got segment camera_rgb_optical_frame
[robot_state_publisher-3] [INFO] [1721654608.191078555] [robot_state_publisher]: got segment caster_back_left_link
[robot_state_publisher-3] [INFO] [1721654608.191085702] [robot_state_publisher]: got segment caster_back_right_link
[robot_state_publisher-3] [INFO] [1721654608.191092846] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-3] [INFO] [1721654608.191099957] [robot_state_publisher]: got segment wheel_left_link
[robot_state_publisher-3] [INFO] [1721654608.191107269] [robot_state_publisher]: got segment wheel_right_link
[spawn_entity.py-4] [INFO] [1721654608.648282427] [spawn_entity]: Spawn Entity started
[spawn_entity.py-4] [INFO] [1721654608.648985957] [spawn_entity]: Loading entity XML from file /home/yusuf/ros2_ws/install/turtlebot3_gazebo/share/turtlebot3_gazebo/models/turtlebot3_waffle/model.sdf
[spawn_entity.py-4] [INFO] [1721654608.650021562] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-4] [INFO] [1721654608.650528827] [spawn_entity]: Waiting for service /spawn_entity
[spawn_entity.py-4] [INFO] [1721654609.406953861] [spawn_entity]: Calling service /spawn_entity
[gzserver-1] [INFO] [1721654609.721660008] [turtlebot3_imu]: <initial_orientation_as_reference> is unset, using default value of false to comply with REP 145 (world as orientation reference)
[spawn_entity.py-4] [INFO] [1721654609.870127923] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [waffle]
[gzserver-1] [INFO] [1721654610.022525579] [turtlebot3_diff_drive]: Wheel pair 1 separation set to [0.287000m]
[gzserver-1] [INFO] [1721654610.022619260] [turtlebot3_diff_drive]: Wheel pair 1 diameter set to [0.066000m]
[gzserver-1] [INFO] [1721654610.024385911] [turtlebot3_diff_drive]: Subscribed to [/cmd_vel]
[gzserver-1] [INFO] [1721654610.027137291] [turtlebot3_diff_drive]: Advertise odometry on [/odom]
[gzserver-1] [INFO] [1721654610.030224473] [turtlebot3_diff_drive]: Publishing odom transforms between [odom] and [base_footprint]
[INFO] [spawn_entity.py-4]: process has finished cleanly [pid 326862]
[gzserver-1] [INFO] [1721654610.046300077] [turtlebot3_joint_state]: Going to publish joint [wheel_left_joint]
[gzserver-1] [INFO] [1721654610.046344120] [turtlebot3_joint_state]: Going to publish joint [wheel_right_joint]
[gzclient-2] gzclient: /usr/include/boost/smart_ptr/shared_ptr.hpp:728: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::rendering::Camera; typename boost::detail::sp_member_access<T>::type = gazebo::rendering::Camera*]: Assertion `px != 0' failed.
[ERROR] [gzclient-2]: process has died [pid 326858, exit code -6, cmd 'gzclient'].

**Comment by badriawan** [comment]
i tried to use gazebo without turtlebot3 world it could run. In contrast, it was error

**Comment by noshluk2** [comment]
Use Htop and kill gzserver, it is running in the background.
