### ISSUE TITLE
OpenCV error for linefollowing roi images 

### ISSUE THREAD

**Issue by badriawan** [Robotisim/robotics_software_engineer#37]
### Describe your issue

for canny_images success but in roi images failed to show camera

[INFO] [launch]: All log files can be found below /home/yusuf/.ros/log/2024-07-30-15-40-16-715830-yusuf-HP-ENVY-Laptop-13-ad1xx-39946
[INFO] [launch]: Default logging verbosity is set to INFO
urdf_file_name : turtlebot3_waffle.urdf
urdf_file_name : turtlebot3_waffle.urdf
[INFO] [gzserver-1]: process started with pid [39994]
[INFO] [gzclient-2]: process started with pid [39996]
[INFO] [robot_state_publisher-3]: process started with pid [39998]
[INFO] [spawn_entity.py-4]: process started with pid [40000]
[INFO] [line_following-5]: process started with pid [40002]
[robot_state_publisher-3] [INFO] [1722328820.400083756] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-3] [INFO] [1722328820.400305709] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1722328820.400333413] [robot_state_publisher]: got segment base_scan
[robot_state_publisher-3] [INFO] [1722328820.400351613] [robot_state_publisher]: got segment camera_depth_frame
[robot_state_publisher-3] [INFO] [1722328820.400368120] [robot_state_publisher]: got segment camera_depth_optical_frame
[robot_state_publisher-3] [INFO] [1722328820.400384927] [robot_state_publisher]: got segment camera_link
[robot_state_publisher-3] [INFO] [1722328820.400400782] [robot_state_publisher]: got segment camera_rgb_frame
[robot_state_publisher-3] [INFO] [1722328820.400416475] [robot_state_publisher]: got segment camera_rgb_optical_frame
[robot_state_publisher-3] [INFO] [1722328820.400432288] [robot_state_publisher]: got segment caster_back_left_link
[robot_state_publisher-3] [INFO] [1722328820.400447927] [robot_state_publisher]: got segment caster_back_right_link
[robot_state_publisher-3] [INFO] [1722328820.400463279] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-3] [INFO] [1722328820.400478697] [robot_state_publisher]: got segment wheel_left_link
[robot_state_publisher-3] [INFO] [1722328820.400494571] [robot_state_publisher]: got segment wheel_right_link
[ERROR] [gzserver-1]: process has died [pid 39994, exit code 255, cmd 'gzserver /home/yusuf/ros2_ws/install/robot_sensing/share/robot_sensing/world/linefollowing.world -slibgazebo_ros_init.so -slibgazebo_ros_factory.so -slibgazebo_ros_force_system.so'].
[spawn_entity.py-4] [INFO] [1722328821.712413122] [spawn_entity]: Spawn Entity started
[spawn_entity.py-4] [INFO] [1722328821.713749226] [spawn_entity]: Loading entity XML from file /opt/ros/humble/share/turtlebot3_gazebo/models/turtlebot3_waffle/model.sdf
[spawn_entity.py-4] [INFO] [1722328821.716282296] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-4] [INFO] [1722328821.717277073] [spawn_entity]: Waiting for service /spawn_entity
[spawn_entity.py-4] [INFO] [1722328821.727562098] [spawn_entity]: Calling service /spawn_entity
[spawn_entity.py-4] [INFO] [1722328822.465530301] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [waffle]
[INFO] [spawn_entity.py-4]: process has finished cleanly [pid 40000]

### Steps to reproduce ( commands you ran - in order )

ros2 launch robot_sensing line_world.launch

node script : 
#include <chrono>
#include <functional>
#include <memory>
#include <string>
#include <cmath>
#include "rclcpp/rclcpp.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "sensor_msgs/msg/image.hpp"
#include "cv_bridge/cv_bridge.h"
#include "opencv2/opencv.hpp"

using namespace std::chrono_literals;

class LineFollowing : public rclcpp::Node
{
public:
  LineFollowing()
  : Node("line_follower")
  {
    this->declare_parameter<int>("lower_threshold",200);
    this->declare_parameter<int>("upper_threshold",250);

    _subscriber = this->create_subscription<sensor_msgs::msg::Image>(
      "/camera/image_raw", 10, std::bind(&LineFollowing::subCallback, this, std::placeholders::_1));

    _publisher = this->create_publisher<geometry_msgs::msg::Twist>("/cmd_vel", 10);

    // _timer = this->create_wall_timer(
    //   100ms, std::bind(&LineFollowing::timerCallback, this));
  }

private:
  void subCallback(const sensor_msgs::msg::Image::SharedPtr camera_msg)
  {
    //get ros data
    //ros to opencv data
    cv_bridge::CvImagePtr cv_ptr;
    cv_ptr = cv_bridge::toCvCopy(camera_msg,"bgr8");

    cv::Mat gray_image,cannyImage;
    cv::cvtColor(cv_ptr->image , gray_image,cv::COLOR_BGR2GRAY);
    int lower_threshold = this->get_parameter("lower_threshold").as_int();
    int upper_threshold = this->get_parameter("upper_threshold").as_int();
    //edge segmentation
    cv::Canny(gray_image,cannyImage,lower_threshold,upper_threshold);

    int row = 150, column = 0;
    //boundaries dari pixel yang mau di proses
    cv::Mat roi = cannyImage(cv::Range(row, row + 240), cv::Range(column, column + 640));

    //piksel yang menunjukkan tepi/edge/objek disimpan dalam edge 
    std::vector<int> edge;
    for (int i = 0; i < 640; ++i) {
      if (roi.at<uchar>(160, i) == 255) {
        edge.push_back(i);
      }
    }
    
    if (!edge.empty()){
    int line = edge[1]-edge[0];
    int mid_line = line + line/2;
    int mid_robot = 640/2;

    cv::circle(roi,cv::Point(mid_line,160),2,cv::Scalar(255,255,255),-1);
    cv::circle(roi,cv::Point(mid_robot,160),5,cv::Scalar(255,255,255),-1);

    cv::imshow("Image", roi);
    cv::waitKey(1);
  }
  }

    //show using opencv
    // cv::namedWindow("Image", cv::WINDOW_NORMAL);
    // cv::resizeWindow("Image", 600, 400);

  //    // Process Canny image to find the line's midpoint
  //   int row = 150, column = 0;
  //   cv::Mat roi = cannyImage(cv::Range(row, row + 240), cv::Range(column, column + 640));

  //   std::vector<int> edge;
  //   for (int i = 0; i < 640; ++i) {
  //     if (roi.at<uchar>(160, i) == 255) {
  //       edge.push_back(i);
  //     }
  //   }

  //   if (!edge.empty()) {
  //     int midArea = edge.back() - edge.front();
  //     int midPoint = edge.front() + midArea / 2;
  //     int robotMidPoint = 640 / 2;

  //     // Calculate error and adjust robot's direction
  //     // double error = robotMidPoint - midPoint;
  //     // velocityMsg.linear.x = 0.1;
  //     // if (error < 0) {
  //     //   velocityMsg.angular.z = -_angularVel;
  //     // } else {
  //     //   velocityMsg.angular.z = _angularVel;
  //     // }

  //     // _publisher->publish(velocityMsg);

  //     // Visualization
  //     cv::circle(roi, cv::Point(midPoint, 160), 2, cv::Scalar(255, 255, 255), -1);
  //     cv::circle(roi, cv::Point(robotMidPoint, 160), 5, cv::Scalar(255, 255, 255), -1);
  //     cv::imshow("Image", roi);
  //     cv::waitKey(1);
  //   }
  // }

//   void timerCallback()
//   {
//     auto cmd = geometry_msgs::msg::Twist();
//     RCLCPP_INFO(this->get_logger(), "Pose x: '%f', y: '%f', theta: '%f'", cmd);

//     _publisher->publish(cmd);
//   }

  rclcpp::TimerBase::SharedPtr _timer;
  rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr _subscriber;
  rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr _publisher;
  size_t _count;

};

int main(int argc, char * argv[])
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<LineFollowing>());
  rclcpp::shutdown();
  return 0;
}

### What was the expected result?

it must show the roi image with circle 

### Put here any screenshots or videos link

![Screenshot from 2024-07-30 15-41-09](https://github.com/user-attachments/assets/953c1873-8a68-4247-bd43-caf35d6e1a35)

**Comment by issaiass** [comment]
try to add a workaroun.

The workaround could be:

if no edges detected
   load the previous edges to the variable edges
if edge detected
    save to a variable named previous edge the actual edges

...
makke detection and correction of position and angles
...

**Comment by badriawan** [comment]
Thats great , thank you for your help bro
